INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-09-21', '2021-09-21', '12:15:00', '14:00:00');
INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-09-22', '2021-09-22', '12:15:00', '14:00:00');
INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-09-23', '2021-09-23', '12:15:00', '14:00:00');
INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-09-24', '2021-09-24', '12:15:00', '14:00:00');
INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-09-25', '2021-09-25', '12:15:00', '14:00:00');
INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-07-11', '2021-08-21', '07:00:00', '07:00:00');
INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-08-22', '2021-08-22', '07:00:00', '07:00:00');
INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-06-23', '2021-07-23', '07:00:00', '07:00:00');
INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-05-24', '2021-04-24', '07:00:00', '07:00:00');
INSERT INTO time_periods(start_date, end_date, start_time, end_time) VALUES ('2021-07-25', '2021-09-01', '07:00:00', '07:00:00');
INSERT INTO vacations(description, time_period_id) VALUES ('vacation description', 6);
INSERT INTO vacations(description, time_period_id) VALUES ('vacation description', 7);
INSERT INTO vacations(description, time_period_id) VALUES ('vacation description', 8);
INSERT INTO vacations(description, time_period_id) VALUES ('vacation description', 9);
INSERT INTO vacations(description, time_period_id) VALUES ('vacation description', 10);
INSERT INTO vacations(description, time_period_id) VALUES ('vacation description', 10);
INSERT INTO classrooms(capacity) VALUES (50);
INSERT INTO classrooms(capacity) VALUES (100);
INSERT INTO classrooms(capacity) VALUES (70);
INSERT INTO classrooms(capacity) VALUES (20);
INSERT INTO classrooms(capacity) VALUES (30);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Barbaris','Arachis','2002-01-21', 'male', 1);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Klementy','Tatarin','2001-05-23', 'male', 2);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Margarita','Seniorita','2000-03-15', 'female', 2);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Martin','Luter','2003-10-21', 'male', 3);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Kvas','Taras','1998-11-11', 'male', 1);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Puck','Puckich','1998-08-21', 'male', 3);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Transkopter','Optic','2000-03-15', 'male', 1);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Kventin','Tackimichi','1997-05-12', 'male', 2);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Illia','Varlamov','2000-01-06', 'male', 1);
INSERT INTO students(firstname, lastname, date_of_birth, gender, study_year) VALUES ('Vitaliy','Cal','2000-07-19', 'male', 3);
INSERT INTO teachers(firstname, lastname, date_of_birth, gender, vacation_id, working_hours_id) VALUES ('Ilon', 'Mask', '1965-12-12', 'male', 1, 5);
INSERT INTO teachers(firstname, lastname, date_of_birth, gender, vacation_id, working_hours_id) VALUES ('Shaverma', 'Lavashnaya', '1973-11-30', 'female', 2, 4);
INSERT INTO teachers(firstname, lastname, date_of_birth, gender, vacation_id, working_hours_id) VALUES ('Onion', 'Ringus', '1987-10-01', 'male', 3, 3);
INSERT INTO teachers(firstname, lastname, date_of_birth, gender, vacation_id, working_hours_id) VALUES ('Dungeon', 'Master', '1977-08-01', 'male', 4, 2);
INSERT INTO teachers(firstname, lastname, date_of_birth, gender, vacation_id, working_hours_id) VALUES ('Alekley', 'Makaronich', '1978-03-05', 'male', 5, 1);
INSERT INTO subjects(name, description, supervisor_id) VALUES ('math','some description',1);
INSERT INTO subjects(name, description, supervisor_id) VALUES ('oop','more description',2);
INSERT INTO subjects(name, description, supervisor_id) VALUES ('algo','even more description',3);
INSERT INTO lectures(subject_id, teacher_id, time_period_id, classroom_id) VALUES (3,2,3,1);
INSERT INTO lectures(subject_id, teacher_id, time_period_id, classroom_id) VALUES (1,1,2,3);
INSERT INTO lectures(subject_id, teacher_id, time_period_id, classroom_id) VALUES (2,3,1,2);
INSERT INTO groups(name) VALUES ('k-15');
INSERT INTO groups(name) VALUES ('f-11');
INSERT INTO groups(name) VALUES ('r-10');
INSERT INTO groups(name) VALUES ('b-05');
INSERT INTO lectures_groups(lecture_id, group_id) VALUES (1,2);
INSERT INTO lectures_groups(lecture_id, group_id) VALUES (1,1);
INSERT INTO lectures_groups(lecture_id, group_id) VALUES (1,3);
INSERT INTO lectures_groups(lecture_id, group_id) VALUES (3,1);
INSERT INTO lectures_groups(lecture_id, group_id) VALUES (2,4);
INSERT INTO lectures_groups(lecture_id, group_id) VALUES (2,1);
INSERT INTO lectures_groups(lecture_id, group_id) VALUES (2,2);
INSERT INTO lectures_groups(lecture_id, group_id) VALUES (3,2);
INSERT INTO students_groups(student_id, group_id) VALUES (1,1);
INSERT INTO students_groups(student_id, group_id) VALUES (2,1);
INSERT INTO students_groups(student_id, group_id) VALUES (3,1);
INSERT INTO students_groups(student_id, group_id) VALUES (4,2);
INSERT INTO students_groups(student_id, group_id) VALUES (5,2);
INSERT INTO students_groups(student_id, group_id) VALUES (6,2);
INSERT INTO students_groups(student_id, group_id) VALUES (8,3);
INSERT INTO students_groups(student_id, group_id) VALUES (7,3);
INSERT INTO students_groups(student_id, group_id) VALUES (9,4);
INSERT INTO subjects_teachers(teacher_id, subject_id) VALUES (1,1);
INSERT INTO subjects_teachers(teacher_id, subject_id) VALUES (1,2);
INSERT INTO subjects_teachers(teacher_id, subject_id) VALUES (2,3);
INSERT INTO subjects_teachers(teacher_id, subject_id) VALUES (2,1);
INSERT INTO subjects_teachers(teacher_id, subject_id) VALUES (3,2);
INSERT INTO subjects_teachers(teacher_id, subject_id) VALUES (3,1);